autoDiscovery:
  clusterName: eks-demo

awsRegion: eu-central-1

extraArgs:
  skip-nodes-with-system-pods: true

rbac:
  create: true
  serviceAccount:
    create: true
    name: "cluster-autoscaler"
    annotations: {eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/eks-demo-irsa-cluster-autoscaler}

