replicaCount: 3

controller:
  serviceAccount:
    create: true
    name: efs-csi-controller-sa
    annotations: {eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/eks-demo-irsa-efs-csi}
    
storageClasses:
  - name: efs
    annotations:
      storageclass.kubernetes.io/is-default-class: "false" # true
    parameters:
      provisioningMode: efs-ap
      fileSystemId: fs-2dfg56hcfg623fdf # Replace with EFS file system id
      directoryPerms: "700"
      gidRangeStart: "1000" # optional
      gidRangeEnd: "2000" # optional
      basePath: "/dynamic_provisioning"
    reclaimPolicy: Delete
    volumeBindingMode: Immediate