apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloopbackoff-deployment
  labels:
    app: crashloopbackoff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloopbackoff
  template:
    metadata:
      labels:
        app: crashloopbackoff
    spec:
      containers:
      - name: crashloop
        image: thenaim/crashloopbackoff:latest

