global:
  name: consul
server:
  replicas: 3
  storage: 1Gi # 5Gi
#  storageClass: microk8s-hostpath
  resources:
    requests:
      memory: 128Mi #256Mi
      cpu: 100m #200m
    limits:
      memory: 256Mi #512Mi
      cpu: 200m #500m

ui:
  ingress:
    enabled: true
    pathType: Prefix
    hosts:
      - host: consul.local.naim.run
        paths:
          - /