global:
  name: consul
server:
  replicas: 1

ui:
  ingress:
    enabled: true
    pathType: Prefix
    hosts:
      - host: consul.local.naim.run
        paths:
          - /

#  storage: 1Gi
#  resources:
#    requests:
#      memory: 128Mi
#      cpu: 100m
#    limits:
#      memory: 192Mi
#      cpu: 150m