---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: handy-goshawk-deployment
  labels:
    app: handy-goshawk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handy-goshawk
  template:
    metadata:
      labels:
        app: handy-goshawk
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: handy-goshawk-service
spec:
  selector:
    app: handy-goshawk
  ports:
    - protocol: TCP
      port: 80
      nodePort: 32321
  type: NodePort