---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magnetic-bluejay-deployment
  labels:
    app: magnetic-bluejay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magnetic-bluejay
  template:
    metadata:
      labels:
        app: magnetic-bluejay
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: magnetic-bluejay-service
spec:
  selector:
    app: magnetic-bluejay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80