apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
  namespace: test
spec:
  serviceName: "date-alpine"
  replicas: 1
  selector:
    matchLabels:
      app: date-alpine
  template:
    metadata:
      labels:
        app: date-alpine
    spec:
      containers:
        - name: date-alpine
          image: alpine
          command: ["/bin/sh"]
          args: ["-c", "while true; do date >> /data/log; sleep 5; done"]
          volumeMounts:
            - name: app-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: app-data
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1Gi


