controller:
  serviceAccount:
    create: true
    name: ebs-csi-controller-sa
    annotations: {eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/eks-demo-irsa-ebs-csi}
  
storageClasses:
  - name: ebs
    annotations:
      storageclass.kubernetes.io/is-default-class: "true" # false
    volumeBindingMode: Immediate
    reclaimPolicy: Delete # Retain