apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: date-writer-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: ebs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: date-writer
spec:
  containers:
    - name: date-writer
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /data/out.txt; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: date-writer-pvc