serviceAccount:
  create: true
  annotations: {eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/eks-demo-irsa-external-dns}
  name: "external-dns"

sources:
  - service
  - ingress
policy: sync
registry: txt
txtOwnerId: "eks-demo" # EKS Cluster name
domainFilters: [naim.run] # Route53 hosted zone # Multiple domain domainFilters: [naim.run, demo.com]
provider: aws